CREATE TABLE IF NOT EXISTS password_entries (
    entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    service_name VARCHAR(255) NOT NULL,
    url VARCHAR(500),
    login VARCHAR(255) NOT NULL,
    password_encrypted VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_password_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);