INSERT INTO PASSWORD_GEN_SETTINGS (USER_ID, LENGTH, MIN_NUM_OF_SPEC_CHARS, MIN_NUM_OF_DIGITS, HAS_LOWERCASE, HAS_UPPERCASE, HAS_SPECIAL, HAS_DIGITS) VALUES
    (1, 12, 2, 2, TRUE, TRUE, TRUE, TRUE);

INSERT INTO PASSWORD_GEN_SETTINGS (USER_ID, LENGTH, MIN_NUM_OF_SPEC_CHARS, MIN_NUM_OF_DIGITS, HAS_LOWERCASE, HAS_UPPERCASE, HAS_SPECIAL, HAS_DIGITS) VALUES
    (2, 24, 2, 2, TRUE, TRUE, TRUE, TRUE);